###**Demonstração NumPY**
###**Disciplina** - Introdução a Ciência de Dados - Univesp
###**Prof**. Dr. José Eduardo Santarem



# Importando Biblioteca

In [4]:
import numpy as np

**Gerando Dados Aleatórios**

**NDArray de 2x3 (Duas Lista com 3º Elementos)**


In [ ]:
dados=np.random.rand(2,3)

In [ ]:
#Verificando o Tipo de Dado; (Array)

dados.dtype


dtype('float64')

**Tamanho e quantidade de dimensões**

In [ ]:
dados.shape

(2, 3)

In [ ]:
dados.ndim

2

**Criar ndarray usando a Função Array**


In [ ]:
lista = [1,2,4,1.25,0.50]

my_nd = np.array(lista)


#Visualizando o ndarry criado;

my_nd

array([1.  , 2.  , 4.  , 1.25, 0.5 ])

In [ ]:
my_lista = [[1,2,4,5], [5,6,7,8]]
my_array = np.array(my_lista)

my_lista

[[1, 2, 4, 5], [5, 6, 7, 8]]

**Outras Maneiras de Criar Array**

In [ ]:
dados_zero = np.zeros(10)

dados

array([[0.28656199, 0.83866673, 0.71134282],
       [0.21836908, 0.53689189, 0.62549952]])

In [ ]:
meus_dados = np.zeros((2,3)) #Criando um Array com duas dimensões e três valores;

meus_dados

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
dados_one = np.ones(5)

dados_one

array([1., 1., 1., 1., 1.])

In [ ]:
dados_seq = np.arange(10) #Criando Valores Sequencias; 


dados_seq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
dados_news = np.arange(0, 20, 2)

dados_news



array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
dados_news.dtype

dtype('int64')

In [ ]:
news_dados = dados_news.astype(np.float64)

In [ ]:
news_dados

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [ ]:
news_dados.dtype

dtype('float64')

#Aritmética com Arrays

In [5]:
meus_dados = np.array([[1,2,3],[4,5,6]])

In [6]:
meus_dados

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
meus_dados * meus_dados

array([[ 1,  4,  9],
       [16, 25, 36]])

In [8]:
meus_dados - meus_dados

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
1 / meus_dados

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [10]:
novos_dados = meus_dados + meus_dados 

In [11]:
meus_dados > novos_dados 

array([[False, False, False],
       [False, False, False]])

#Indexação


In [12]:
meus_dados[1]

array([4, 5, 6])

In [13]:
meus_dados[1] = 7

In [15]:
meus_dados

array([[1, 2, 3],
       [7, 7, 7]])

In [22]:
new = meus_dados[1].copy() #Copiando o valor de um Indice e atribuindo a uma nova váriavel;

In [23]:
new

array([7, 7, 7])

#Arrays Dimensionais


In [30]:
news=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [31]:
news[1, 2]

6

#Máscaras

In [32]:
news

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mascara = (news > 100)

In [38]:
news[news<30] = 100

In [39]:
news

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

#Transposição


In [41]:
dataset = np.arange(15).reshape((3, 5))

In [42]:
dataset

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
dataset.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

#Multiplicação de Matriz com DOTS

In [44]:
np.dot(dataset.T,dataset)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [ ]:
# Outras Funções Revelantes da Biblioteca NumPy:

#in, cos, power, mod, sqrt;